### ISSUE TITLE
Validation fails on an empty list

### ISSUE THREAD

**Issue by dhimmel** [JakobGM/patito#103]
The following model validation fails on an empty list:

```py
import polars as pl
from patito import Model

class TestModel(Model):
    list_field: list[str]

df = pl.DataFrame({"list_field": [["a", "b"], []]})
TestModel.validate(df)
```

With the error message:

```
DataFrameValidationError: 1 validation error for TestModel
list_field
  1 missing value in lists (type=value_error.missingvalues)
```

I would expect an empty list to validate as `list[str]`, at least Pydantic thinks so:

```py
from pydantic import BaseModel

class TestPydanticModel(BaseModel):
    list_field: list[str]

TestPydanticModel(list_field=[])  # happy
```

**Comment by dhimmel** [comment]
Changing to `list_field: list[str | None]` passes validation.

**Comment by dsgibbons** [comment]
Can you please rerun this from the main branch instead of the latest release and see if this is still an issue? If this is still an issue, it should be a pretty easy fix.

**Comment by dsgibbons** [comment]
Ok I confirm this is present on main. Thank you for raising this.
