### ISSUE TITLE
Optional list field with nested model fails to validate

### ISSUE THREAD

**Issue by dhimmel** [JakobGM/patito#104]
```py
import polars as pl
from patito import Model

class TestStructModel(Model):
    nested_struct_field: int

class TestModel(Model):
    list_field: list[TestStructModel] | None

df = pl.DataFrame({"list_field": [[{"nested_struct_field": 1}, {"nested_struct_field": 2}]]})
TestModel.validate(df)
```

fails with:

```
    143 column_subset = columns or dataframe.columns
    144 if not allow_missing_columns:
    145     # Check if any columns are missing

AttributeError: type object 'list' has no attribute 'columns'
```

If I change the signature to `list_field: list[TestStructModel]` by removing the optionality, there is no failure.

**Comment by dsgibbons** [comment]
This was fixed by #100. I'm hoping we can get a release soon so users don't need to pip install from the main branch. Any news on when the next release will be @thomasaarholt @JakobGM?

**Comment by dhimmel** [comment]
Ah okay, so this appears to be a duplicate of https://github.com/JakobGM/patito/issues/85.

+1 to frequent releases while the core functionality is still being ironed out. Thanks for a cool project and this plugging this missing functionality in polars.

**Comment by thomasaarholt** [comment]
Just released now. Apologies for the slow response time while I'm on parental leave! Hard to fine the time 😓

**Comment by dsgibbons** [comment]
No worries @thomasaarholt, hope you're all doing well.

**Comment by dhimmel** [comment]
Much appreciated @thomasaarholt. BTW I'm not seeing a release on PyPI yet: https://pypi.org/project/patito/0.8.0/

**Comment by thomasaarholt** [comment]
There! Took me a lot of tries and I still don't understand why it didn't work before my latest iteration of [release.yml,](https://github.com/JakobGM/patito/blob/main/.github/workflows/release.yml) but there is now a new release on pypi!

**Comment by dsgibbons** [comment]
Thanks @thomasaarholt - much appreciated 🙏
