### ISSUE TITLE
Iterate over rows of a `Model` and with pydantic objects

### ISSUE THREAD

**Issue by gab23r** [JakobGM/patito#115]
It would be nice to be able to iterate over a Model. 
Something along those lines:
```python
class DataFrame(pl.DataFrame, Generic[ModelType]):
    ...
    def iter_models(self, validate: bool = True) -> list[ModelType]:
        if validate:
            self.model.validate(self)
    
        pydantic_objs = []
        for r in df_model.rows(named=True):
            pydantic_objs.append(self.model.model_construct(**r))
    
        return pydantic_objs

```
If accepted, I am willing to take this one

**Comment by thomasaarholt** [comment]
Hello! Could you expand on how you would use this? I note that we already have `pt.Model.iter_models` and `pt.DataFrame.iter_models`, but I think you knew that, and I'm failing to spot what behaviour you desire.
