### ISSUE TITLE
[FEAT] Upgrade to `Pydantic v2`

### ISSUE THREAD

**Issue by jjfantini** [JakobGM/patito#28]
This will allow multiple benefits.

Use cases:
- multiple values allowed for aliases with `AliasChoices` and `AliasGenerator`

I need to validate a df that can have multiple names for a specific column. Let's say it could be `col1` or `col[1-10]'. 

I have a df that is created, and the column names can be a few different things but the same column, and I need a way to validate all the possible names. I've tried multiple things, custom validators, creating a model dynamically, and they have yet to work.

**Comment by jjfantini** [comment]
@JakobGM

**Comment by brendancooley** [comment]
Running list of todos here, perhaps we can farm these off into narrower issues if the implied solution is precise enough:

- [x] `pydantic.error_wrappers.ErrorWrapper` has been deprecated, need to update validation error reporting to conform to pydantic's new style
    * It looks like @thomasaarholt has some work on #4 to support the printing of data frame validation error messages
    * the library currently handles dataframe validation in `patito.validation._find_errors`, but pydantic expects validation to occur at the model level, which makes conforming to pydantic's error handling style somewhat difficult. Perhaps we could brainstorm a more "pydantic2" way of running validation on dataframes.
- [x] subclass/extend `pydantic`'s `Field` (or `FieldInfo`) to handle `patito` custom attributes (`unique`, `derived_from`, `dtype`, `constraints`, others?)
- [x] workaround (or `polars`-side solution) to support the json serialization of `polars` `DataType` and `Expr` objects, to address serialization errors when calling `BaseModel.model_json_schema()` on models that contain `polars` elements.


---
some wip on validators [here](https://github.com/JakobGM/patito/commit/88cfdb5e71f02e6e2dacbe6beaa40030268c9cd5). The data frame validation logic doesn't quite map to the way pydantic v2 expects validation to occur, so I more or less ported over the pydantic v1 validation error reporting system into patito. It looks like this is where @thomasaarholt was headed with his PR. all tests in `test_validators` now passing except those that have serialization issues with `json_schema_extra` fields.

---
wip on extending `FieldInfo` [here](https://github.com/JakobGM/patito/commit/2c7c2b40850f0ef4550c604ba79c0036a9cce529)

---
fully operational prototype for the upgrade is up at #32
