### ISSUE TITLE
Release 0.6.0 wasn't published to pipy

### ISSUE THREAD

**Issue by strangemonad** [JakobGM/patito#40]
thanks for this great library and excited to see progress continue. I noticed that the release GH actions pipeline failed for 0.6.0 https://github.com/JakobGM/patito/actions/runs/8066691480.

It would be great to get this release published since it now supports pydantic >2

**Comment by thomasaarholt** [comment]
Yep, I noticed it. The requirements for release were super stringent. I'm going to reduce the requirements, make a release and then work on fixing the issues. Just need to find the time to do so, hopefully in the next few days.

**Comment by thomasaarholt** [comment]
We are live now!
https://pypi.org/project/patito/

**Comment by strangemonad** [comment]
wow that was fast. confirmed it works in my project. ❤️
