### ISSUE TITLE
Nested literals not evaluated

### ISSUE THREAD

**Issue by ion-elgreco** [JakobGM/patito#68]
Nested literals in a list are not properly evaluated for invalid values, see example below:

```python
import patito as pt
import polars as pl
from typing import Literal
class TestModel(pt.Model):
    foo: list[Literal['abc']]  = pt.Field(dtype=pl.List(pl.Utf8))
    
    
df = pl.DataFrame({
    "foo": [['wrong']]
})

TestModel.validate(df)
```

This should actually throw an error

**Comment by ion-elgreco** [comment]
@thomasaarholt @brendancooley fyi ;)

**Comment by thomasaarholt** [comment]
Thanks! I'll see if I can find time to look at it this week!

**Comment by brendancooley** [comment]
Taking a peak now, hopefully quick fix
